# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=2, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0447\u0435\u0442\u0430')),
                ('bill_name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0430')),
                ('bill_type', models.CharField(choices=[('\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439', 'active'), ('\u041f\u0430\u0441\u0441\u0438\u0432\u043d\u044b\u0439', 'passive'), ('\u0410\u043a\u0442\u0438\u0432\u043d\u043e-\u041f\u0430\u0441\u0441\u0438\u0432\u043d\u044b\u0439', 'active_passive')], max_length=30, verbose_name='\u0422\u0438\u043f \u0441\u0447\u0435\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u0447\u0435\u0442',
                'verbose_name_plural': '\u0421\u0447\u0435\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('\u0418\u041f', '\u0418\u041f'), ('\u041e\u041e\u041e', '\u041e\u041e\u041e'), ('\u041e\u0410\u041e', '\u041e\u0410\u041e')], max_length=3, verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f')),
                ('name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('inn', models.CharField(max_length=20, verbose_name='\u0418\u041d\u041d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateField(blank=True, default=datetime.datetime(2017, 4, 3, 12, 3, 51, 756000), null=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='\u043d\u0430\u0447\u0430\u043b\u043e \u043f\u0435\u0440\u0438\u043e\u0434\u0430')),
                ('stop_date', models.DateField(blank=True, default=None, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0446 \u043f\u0435\u0440\u0438\u043e\u0434\u0430')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043e\u0442\u0447\u0435\u0442\u0430')),
                ('report', models.FileField(blank=True, null=True, upload_to='D:\\www\\untitled\\JohnyRabbit/uploads/', verbose_name='\u0424\u0430\u0439\u043b \u043e\u0442\u0447\u0435\u0442\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 4, 3, 12, 3, 51, 756000), verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f')),
                ('summ', models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('info', models.CharField(default=None, max_length=50, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
                ('contractor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.Contractor', verbose_name='\u041a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0422\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u0422\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Bill', verbose_name='\u0421\u0447\u0435\u0442')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043d\u0438\u0433\u0430')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0431\u043e\u0447\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0447\u0438\u0435 \u0433\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='accounting.WorkGroup', verbose_name='\u041a\u0440\u0435\u0434\u0438\u0442'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='debet', to='accounting.WorkGroup', verbose_name='\u0414\u0435\u0431\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='bills',
            field=models.ManyToManyField(blank=True, null=True, related_name='bills', to='accounting.WorkGroup', verbose_name='\u0421\u0447\u0435\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
