# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(max_length=99, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_report',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 4, 12, 2, 13, 834000), null=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 4, 12, 2, 13, 834000), verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f'),
        ),
    ]
