# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20170404_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0447\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439', 'active'), ('\u041f\u0430\u0441\u0441\u0438\u0432\u043d\u044b\u0439', 'passive'), ('\u0410\u043a\u0442\u0438\u0432\u043d\u043e-\u041f\u0430\u0441\u0441\u0438\u0432\u043d\u044b\u0439', 'active_passive')], max_length=30, null=True, verbose_name='\u0422\u0438\u043f \u0441\u0447\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_report',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 4, 12, 5, 12, 516000), null=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 4, 12, 5, 12, 516000), verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f'),
        ),
    ]
